### ISSUE TITLE
Can't open Good Lock after running light debloat.

### ISSUE THREAD

**Issue by Jackboy001** [invinciblevenom/debloat_samsung_android#10]
After running light debloat script, Good Lock will close immediately after I open it.
I've tried to install looks like theme related packages back (com.samsung.android.themestore, com.samsung.android.themecenter) but the problem persist.
Is there other packages I have to install back to make Good Lock working? 
Thanks for your answer in advance!

**Comment by Jackboy001** [comment]
After reinstalling these theme related packages, still need a reboot and a reinstall of Good Lock.
Problem solved. Thanks.

**Comment by invinciblevenom** [comment]
> After reinstalling these theme related packages, still need a reboot and a reinstall of Good Lock. Problem solved. Thanks.

You should always perform a reboot post installing/uninstalling system apps.
