### ISSUE TITLE
Can't enable Cellular Data

### ISSUE THREAD

**Issue by ghost** [invinciblevenom/debloat_samsung_android#11]
after using the heavy debloat, i cant enable my mobile celular data, is there any commands to fix this?

**Comment by ghost** [comment]
btw im using samsung a10s, os android 11 firmware, stock rom

**Comment by invinciblevenom** [comment]
> btw im using samsung a10s, os android 11 firmware, stock rom

Is your phone carrier device like T-mobile, Sprint etc.?

**Comment by invinciblevenom** [comment]
> after using the heavy debloat, i cant enable my mobile celular data, is there any commands to fix this?

Can you confirm if calls are working perfectly and it's not a network side issue?

**Comment by ghost** [comment]
> > after using the heavy debloat, i cant enable my mobile celular data, is there any commands to fix this?
> 
> Can you confirm if calls are working perfectly and it's not a network side issue?

first of all, i wanted to tell you that my phone calls is perfectly fine, and its not a network side issue, beacuse before i used this debloat script, my mobile celular data is working perfectly fine, and after using it, it wont be enabled, i tried to format data, and boom, the mobile celuler data is wokring again, i think its 100% bc the debloat script

**Comment by invinciblevenom** [comment]
> > > after using the heavy debloat, i cant enable my mobile celular data, is there any commands to fix this?
> > 
> > 
> > Can you confirm if calls are working perfectly and it's not a network side issue?
> 
> first of all, i wanted to tell you that my phone calls is perfectly fine, and its not a network side issue, beacuse before i used this debloat script, my mobile celular data is working perfectly fine, and after using it, it wont be enabled, i tried to format data, and boom, the mobile celuler data is wokring again, i think its 100% bc the debloat script

Thank you for confirming. I'll look into the debloat list again and update here.

**Comment by invinciblevenom** [comment]
> > btw im using samsung a10s, os android 11 firmware, stock rom
> 
> Is your phone carrier device like T-mobile, Sprint etc.?

Please tell this

**Comment by ghost** [comment]
sorry for the late answer, and the answer is, yeah, im using device carrier ( SIM Card )

**Comment by ghost** [comment]
> sorry for the late answer, and the answer is, yeah, im using device carrier ( SIM Card )

when im using the debloat script ( the heavy debloat script one ) , and then i reboot, the celular data is just doesnt work anymore, thats all

**Comment by invinciblevenom** [comment]
> sorry for the late answer, and the answer is, yeah, im using device carrier ( SIM Card )

Which carrier?

**Comment by invinciblevenom** [comment]
> > sorry for the late answer, and the answer is, yeah, im using device carrier ( SIM Card )
> 
> when im using the debloat script ( the heavy debloat script one ) , and then i reboot, the celular data is just doesnt work anymore, thats all

I'll recommend you not to use heavy debloat script then.
