### ISSUE TITLE
Script for Samsung account users

### ISSUE THREAD

**Issue by invinciblevenom** [invinciblevenom/debloat_samsung_android#15]
I need suggestions from everyone, should we have a script (alternate to Light debloat) which keeps Samsung account intact for users who need same?

**Comment by Not4u94** [comment]
I would like to use an alternative script to maintain the basic functions of Google and Samsung services, including the Samsung account, Galaxy store or basic Google services, or while using the script, be able to Select which application will be deleted. For example, I would like to keep the photo editor features in the gallery, but I don't need bixby related features or AR overlays in the camera app at all in One ui 6.1 on Galaxy s21. I need a script that will maintain the basic functionality of Google/Samsung Galaxy services while reducing battery drain and memory/CPU usage.

**Comment by invinciblevenom** [comment]
> I would like to use an alternative script to maintain the basic functions of Google and Samsung services, including the Samsung account, Galaxy store or basic Google services, or while using the script, be able to Select which application will be deleted. For example, I would like to keep the photo editor features in the gallery, but I don't need bixby related features or AR overlays in the camera app at all in One ui 6.1 on Galaxy s21. I need a script that will maintain the basic functionality of Google/Samsung Galaxy services while reducing battery drain and memory/CPU usage.

Any specific requirement like this can be met by enabling the required apps/features after running the debloat script

**Comment by invinciblevenom** [comment]
Thanks to @Smagankabel for testing the Basic debloat script. I'll make a new release soon.
