### ISSUE TITLE
A quick question related to Galaxy AI on S24 Ultra

### ISSUE THREAD

**Issue by ragedriver** [invinciblevenom/debloat_samsung_android#17]
Hello and sorry for the trouble,after using the heavy debloat the galaxy ai stops working entirely,what app do I need to enable for the advanced intelligence (galaxy ai) to work again on the S24 Ultra? Thanks in advance and very nice work on those amazing scripts!
![Screenshot_20240808_183604_Settings](https://github.com/user-attachments/assets/e8c190ab-7fc9-4890-a6b2-5b33bfbdbb1c)
![Screenshot_20240808_183604_Settings](https://github.com/user-attachments/assets/6301adef-fef2-4138-be42-faaf688b09a7)

**Comment by invinciblevenom** [comment]
Try revert basic debloat script [from here](https://github.com/invinciblevenom/debloat_samsung_android/blob/main/revert/Revert_Basic_debloat.bat). This will enable Samsung Account and other samsung related features, and check if you're able to use AI features.

**Comment by invinciblevenom** [comment]
If the above thing doesn't work, then you'll have to use revert script of heavy debloat, which will enable all the apps which were removed. And after that, just use basic debloat script if you've to keep Samsung account and features intact.

**Comment by invinciblevenom** [comment]
Closing this issue now!
