### ISSUE TITLE
Cant make calls

### ISSUE THREAD

**Issue by ghost** [invinciblevenom/debloat_samsung_android#3]
When I used the full de-bloat script calling and answering calls just crashes the calling app. I usually use the google phone app but uninstalling that and using the Samsung phone app doesn't seem to work either.

**Comment by invinciblevenom** [comment]
Reinstall these apps using command prompt:

`adb shell cmd package install-existing com.samsung.cmh`                                       
`adb shell cmd package install-existing com.samsung.crane`  
`adb shell cmd package install-existing com.sec.unifiedwfc`                            
`adb shell cmd package install-existing com.sec.vsim.ericssonnsds.webapp`
   
P.S. Always mention your model and firmware version while opening an issue.
