### ISSUE TITLE
Can we add the removal for the following apps as well? 

### ISSUE THREAD

**Issue by qy2009** [invinciblevenom/debloat_samsung_android#4]
I have the Samsung Galaxy Tab S7 FE 5G, SM-T738U...

Smart Tutor, 
Device care, 
Digital Wellbeing,
Parental controls, 
Private Share,
Secure Wi-Fi,
Family Link parental controls,
SmartThings Framework,
Daily Board,
Secure Folder,
T-Mobile

thanks!

**Comment by invinciblevenom** [comment]
Can you share the package names so that I can be double sure about each on of them?

**Comment by invinciblevenom** [comment]
> Smart Tutor, Device care, Digital Wellbeing, Private Share, Secure Wi-Fi, SmartThings Framework

You can remove these apps and they are safe!

**Comment by qy2009** [comment]
the only one I think I found is this one: package:com.tmobile.pr.mytmobile
the rest are a bit hard to see the correct package? :(

here is my output:
adb shell cmd package list packages

package:com.sec.android.RilServiceModeApp
package:com.samsung.android.wifi.resources
package:com.google.android.providers.media.module
package:com.sec.android.gallery3d
package:com.samsung.android.widget.pictureframe
package:com.google.android.overlay.modules.permissioncontroller.forframework
package:com.sec.imslogger
package:com.sec.automation
package:com.sec.android.app.servicemodeapp
package:com.sec.android.iaft
package:com.samsung.android.calendar
package:com.wssyncmldm
package:com.samsung.android.inputshare
package:com.samsung.android.providers.factory
package:com.google.android.overlay.modules.cellbroadcastreceiver
package:com.samsung.android.vtcamerasettings
package:com.samsung.android.homemode
package:com.samsung.android.mcfds
package:com.samsung.android.smartface.overlay
package:org.zwanoo.android.speedtest
package:com.samsung.android.knox.kpecore
package:com.samsung.internal.systemui.navbar.sec_gestural_no_hint
package:com.sec.android.app.applinker
package:com.sec.providers.assisteddialing
package:com.android.companiondevicemanager
package:com.samsung.android.lool
package:com.android.mms.service
package:com.android.providers.downloads
package:com.android.bluetoothmidiservice
package:com.sec.facatfunction
package:com.google.android.captiveportallogin
package:com.google.android.networkstack
package:com.android.keychain
package:com.samsung.android.service.aircommand
package:com.google.android.overlay.gmsconfig.asi
package:com.plexapp.android
package:com.microsoft.office.outlook
package:com.sec.android.app.desktoplauncher
package:android.auto_generated_rro_vendor__
package:com.sec.imsservice
package:com.microsoft.emmx
package:com.samsung.android.app.earphonetypec
package:com.sprint.ms.cdm
package:com.samsung.android.localeoverlaymanager
package:com.android.shell
package:com.google.android.adservices.api
package:com.android.inputdevices
package:com.google.android.ondevicepersonalization.services
package:com.samsung.android.incallui
package:com.samsung.android.wifi.softapwpathree.resources
package:com.samsung.android.app.contacts
package:com.google.android.permissioncontroller
package:com.samsung.InputEventApp
package:com.samsung.android.sdk.handwriting
package:com.android.providers.media
package:com.sec.android.sdhms
package:com.android.providers.calendar
package:com.android.providers.blockednumber
package:com.google.android.documentsui
package:com.samsung.android.service.airviewdictionary
package:com.google.android.overlay.modules.documentsui
package:com.samsung.android.networkdiagnostic
package:com.android.proxyhandler
package:com.samsung.app.newtrim
package:com.google.android.overlay.modules.permissioncontroller
package:com.cisco.webex.meetings
package:com.sec.android.app.launcher
package:com.samsung.advp.imssettings
package:com.samsung.android.peripheral.framework
package:com.samsung.android.biometrics.app.setting
package:com.samsung.android.cameraxservice
package:com.android.carrierdefaultapp
package:com.android.backupconfirm
package:com.samsung.android.ConnectivityUxOverlay
package:com.android.mtp
package:com.google.android.gsf
package:com.samsung.knox.securefolder
package:com.microsoft.teams
package:com.samsung.android.providers.contacts
package:com.google.android.syncadapters.calendar
package:com.google.android.overlay.modules.cellbroadcastservice
package:cn.toside.music.mobile
package:com.fluidtouch.noteshelf2
package:com.android.systemui
package:com.android.wallpapercropper
package:com.samsung.android.service.pentastic
package:com.grammarly.android.keyboard
package:com.samsung.accessibility
package:com.llamalab.automate
package:com.vzw.apnlib
package:us.zoom.videomeetings
package:com.samsung.android.app.parentalcare
package:com.google.android.overlay.gmsconfig.geotz
package:com.android.internal.systemui.navbar.gestural
package:com.samsung.android.mtp
package:com.sec.android.desktopmode.uiservice
package:com.samsung.android.appseparation
package:com.sec.sprextension
package:com.google.mainline.adservices
package:com.samsung.android.app.cocktailbarservice
package:com.android.settings.intelligence
package:com.samsung.android.sdk.ocr
package:com.samsung.android.privateshare
package:com.qualcomm.timeservice
package:com.samsung.android.video
package:com.samsung.android.audiomirroring
package:com.android.hotwordenrollment.okgoogle
package:com.wsomacp
package:com.samsung.internal.systemui.navbar.sec_gestural
package:com.sec.android.app.bluetoothagent
package:com.sec.android.Cdfs
package:com.google.android.federatedcompute
package:com.google.android.webview
package:com.google.android.sdksandbox
package:com.google.android.cellbroadcastservice
package:com.samsung.clipboardsaveservice
package:com.android.internal.systemui.navbar.threebutton
package:com.samsung.android.wifi.softap.resources
package:com.android.localtransport
package:android
package:com.samsung.cmh
package:com.samsung.android.networkstack
package:com.sec.modem.settings
package:com.samsung.android.singletake.service
package:com.google.android.overlay.modules.modulemetadata.forframework
package:com.samsung.android.callbgprovider
package:com.android.hotwordenrollment.xgoogle
package:com.samsung.android.container
package:com.samsung.android.bluelightfilter
package:com.samsung.android.smartsuggestions
package:com.sprint.ce.updater
package:com.samsung.android.wcmurlsnetworkstack
package:com.google.android.packageinstaller
package:com.android.se
package:com.android.pacprocessor
package:com.samsung.android.app.clockpack
package:com.sec.hiddenmenu
package:com.sec.location.nfwlocationprivacy
package:com.google.android.safetycenter.resources
package:com.sec.factory.camera
package:com.samsung.android.mdx.quickboard
package:com.android.settings
package:com.tmobile.tuesdays
package:com.android.internal.systemui.navbar.gestural_narrow_back
package:com.google.android.networkstack.tethering
package:com.samsung.android.service.tagservice
package:com.android.cameraextensions
package:com.sprint.ms.smf.services
package:com.samsung.android.app.telephonyui
package:com.microsoft.office.onenote
package:com.android.carrierconfig
package:com.samsung.android.keycustomizationinfobackupservice
package:com.android.internal.systemui.navbar.gestural_wide_back
package:com.android.internal.systemui.onehanded.gestural
package:com.google.android.apps.carrier.carrierwifi
package:com.samsung.android.setting.multisound
package:com.samsung.android.networkstack.tethering.overlay
package:com.android.chrome
package:com.sec.android.app.myfiles
package:com.samsung.android.provider.filterprovider
package:com.samsung.android.dck.timesync
package:com.sec.android.app.ve.vebgm
package:com.samsung.android.app.dressroom
package:com.samsung.android.samsungpositioning
package:android.auto_generated_rro_product__
package:com.samsung.android.service.livedrawing
package:com.sec.android.app.camera
package:com.samsung.android.honeyboard
package:com.samsung.android.server.wifi.mobilewips
package:vendor.qti.hardware.cacert.server
package:com.brave.browser
package:com.android.providers.downloads.ui
package:com.android.ons
package:com.google.android.networkstack.tethering.overlay
package:com.samsung.android.wallpaper.res
package:com.google.android.nearby.halfsheet
package:com.sec.android.app.setupwizard
package:com.samsung.android.allshare.service.fileshare
package:com.android.certinstaller
package:com.samsung.android.secsoundpicker
package:com.android.wifi.resources
package:com.android.wifi.dialog
package:com.rsupport.rs.activity.rsupport.aas2
package:com.qti.snapdragon.qdcm_ff
package:com.microsoft.office.excel
package:com.sprint.w.installer
package:com.android.simappdialog
package:com.android.providers.telephony
package:com.android.wallpaper.livepicker
package:com.samsung.android.dynamiclock
package:com.qualcomm.qti.gpudrivers.lito.api30
package:com.samsung.android.spdfnote
package:com.tmobile.pr.adapt
package:com.personalcapital.pcapandroid
package:com.sec.app.RilErrorNotifier
package:com.samsung.android.privacydashboard
package:com.android.providers.settings
package:com.android.phone
package:com.android.internal.systemui.navbar.gestural_extra_wide_back
package:com.sec.android.app.quicktool
package:com.sec.phone
package:com.samsung.android.location
package:com.google.android.as.oss
package:com.samsung.android.dialer
package:info.kfsoft.force.rotation
package:com.android.location.fused
package:com.android.vpndialogs
package:com.android.uwb.resources
package:com.google.android.overlay.gmsconfig.photos
package:com.google.android.modulemetadata
package:com.sec.android.app.clockpackage
package:com.samsung.android.app.updatecenter
package:com.android.vending
package:com.samsung.android.knox.containercore
package:com.samsung.android.app.notes
package:com.google.android.ext.services
package:com.samsung.android.themecenter
package:com.google.android.overlay.modules.captiveportallogin.forframework
package:com.samsung.android.forest
package:com.sec.factory.cameralyzer
package:com.samsung.android.messaging
package:com.samsung.android.wifi.p2paware.resources
package:com.sec.usbsettings
package:com.google.android.gms.supervision
package:com.google.android.overlay.gmsconfig.gsa
package:com.samsung.android.service.stplatform
package:com.samsung.ssu
package:com.samsung.android.smartmirroring
package:com.google.android.overlay.gmsconfig.common
package:com.android.bluetooth
package:com.google.android.gms
package:com.android.storagemanager
package:com.fobwifi.normal
package:com.tmobile.pr.mytmobile
package:com.samsung.internal.systemui.navbar.gestural_no_hint
package:com.samsung.android.game.gos
package:co.tech.apkgames
package:com.samsung.android.app.smartcapture
package:com.samsung.android.ConnectivityOverlay
package:com.sec.android.soagent
package:com.samsung.android.fast
package:com.google.mainline.telemetry
package:com.samsung.android.providers.media
package:com.samsung.android.app.dofviewer
package:com.android.hotspot2.osulogin
package:com.samsung.android.kgclient
package:com.test.LTEfunctionality
package:com.google.android.connectivity.resources
package:com.sec.android.mimage.photoretouching
package:com.sec.android.dexsystemui
package:com.android.externalstorage
package:com.samsung.unifiedtp
package:com.samsung.android.gru
package:com.samsung.android.scpm
package:com.android.server.telecom

**Comment by invinciblevenom** [comment]
Just remove the packages I have mentioned above. Those are safe to uninstall.

About the other apps, just disable them using adb. It's a safe process and won't cause any issues

**Comment by qy2009** [comment]
is there any apps/tools I can find the exact package name to remove them?

**Comment by invinciblevenom** [comment]
> is there any apps/tools I can find the exact package name to remove them?

You can use Adb App Control [https://adbappcontrol.com/en/](url). 

Check the debloat script and select the apps in this and remove them.

**Comment by invinciblevenom** [comment]
If your query has been resolved. You can close the issue.

Thank you!

**Comment by qy2009** [comment]
thanks, I got them removed :)

here are the app names in case someone else need it:

com.samsung.android.service.stplatform
com.rsupport.rs.activity.rsupport.aas2
com.samsung.android.fast
com.samsung.android.lool
com.samsung.android.forest
com.samsung.android.privateshare
