### ISSUE TITLE
can i enable smart view? also ways to disable update notification.

### ISSUE THREAD

**Issue by humbledsonu** [invinciblevenom/debloat_samsung_android#5]
Hello,

Amazing job in creating a great debloat script. My screen on time is almost similar or bit more side. but screen off, time is increased by 100% in accubattery. before it was just 58hrs, now its more than 130hrs. 

I miss casting phone to my TV, is there any way to enable smartview? also it was in quick panel. 

Anyway to disable update notification permanently??

Thank you very much again.

![photo_2023-10-30_13-09-59](https://github.com/invinciblevenom/debloat_samsung_android/assets/149363540/02c2c677-1b8b-4093-ab4e-dcd9ebd8f153)

**Comment by invinciblevenom** [comment]
To use Casting to TV, enable this app: 
`adb shell cmd package install-existing com.samsung.android.smartmirroring`

To disable system updates, disable the following apps:
`adb shell pm disable-user --user 0 com.wssyncmldm`
`adb shell pm disable-user --user 0 com.sec.android.soagent`
`adb shell pm disable-user --user 0 com.sec.android.systemupdate`

**Comment by humbledsonu** [comment]
Hi Bro. thank you very much. enabled, smartview & also using your monochrome app.. anyway to donate you??
