### ISSUE TITLE
Cannot login to samsung account

### ISSUE THREAD

**Issue by HannesWo** [invinciblevenom/debloat_samsung_android#7]
I used light debloat script in combination with galaxy A54 and one ui 6.0.

I cannot login anymore to my samsung account. For example if I try to enable find my phone, while clicking on it nothing happens. In the samsung health app it says can't set up app error 0x2C#7#131072. I re-enabled all packages which contain .samsung. so I do not know where the fault could lie.

**Comment by invinciblevenom** [comment]
Please run `adb shell cmd package install-existing com.osp.app.signin`

This is the package name for Samsung Account

**Comment by HannesWo** [comment]
Thank you very much! That solved it :D

**Comment by invinciblevenom** [comment]
> Thank you very much! That solved it :D

Welcome ;)
