### ISSUE TITLE
CSC not working anymore.

### ISSUE THREAD

**Issue by snapboss** [invinciblevenom/debloat_samsung_android#9]
after heavy debloat, csc codes not working anymore, even *# 06 # 

Galaxy S10 Plus, one ui 4.1

**Comment by invinciblevenom** [comment]
Run this command in adb and check again
`adb shell cmd package install-existing com.samsung.sec.android.application.csc`

**Comment by invinciblevenom** [comment]
And apologies for late reply :)

**Comment by snapboss** [comment]
Perfect. That worked, thanks a lot :)
